# Generated by Django 3.1.5 on 2021-01-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='name',
            new_name='path',
        ),
    ]
