# Generated by Django 3.1.5 on 2021-01-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210116_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='dir',
            new_name='parent',
        ),
    ]
