# Generated by Django 3.1.5 on 2021-01-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210121_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
