# Generated by Django 3.1.5 on 2021-01-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tz_offset_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
