# Generated by Django 3.1.5 on 2021-01-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_tz_offset_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date_time',
            new_name='date_time_utc',
        ),
    ]
