# Generated by Django 3.1.5 on 2021-05-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210513_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tz_offset_seconds',
            new_name='tz_offset',
        ),
    ]
