# Generated by Django 4.1 on 2022-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_image_thumbnail_alter_attachment_id_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gps_altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='gps_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='gps_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails'),
        ),
    ]
