# Generated by Django 4.1 on 2022-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_image_gps_altitude_image_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
