# Generated by Django 4.1 on 2022-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_image_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color_label',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='pick_label',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
