# Generated by Django 4.1 on 2022-12-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.camera'),
        ),
    ]
