# Generated by Django 4.1 on 2022-12-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_image_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
