# Generated by Django 4.1 on 2022-12-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_camera_make_alter_camera_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
