# Generated by Django 4.1 on 2022-12-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_image_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='file_number_end_idx',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='file_number_start_idx',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
